import type { Metadata } from 'next';
import './globals.css';
import Navbar from '@/components/Navbar';
import Script from 'next/script';
import getCurrentUser from './actions/getCurrentUser';
import ToastProvider from '@/components/ToastProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getCurrentUser();

  return (
    <html lang='en'>
      <body>
        <Navbar currentUser={currentUser} />
        <ToastProvider />

        {children}

        <Script
          src="//dapi.kakao.com/v2/maps/sdk.js?appkey=1d7e86a934a744bd0f2971fa2b7dc1ff&libraries=services,clusterer&autoload=false"
        />
      </body>
    </html>
  );
}
